# Generated by Django 5.0.2 on 2024-02-19 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DisciplineModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipline_image', models.ImageField(upload_to='media')),
                ('discipline_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='CommandModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_image', models.ImageField(upload_to='media')),
                ('command_name', models.CharField(max_length=64)),
                ('command_location', models.CharField(max_length=64)),
                ('command_total_winnings', models.IntegerField()),
                ('command_creation_date', models.DateField()),
                ('command_discipline_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cybersport.disciplinemodel')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_image', models.ImageField(upload_to='media')),
                ('player_name', models.CharField(max_length=64)),
                ('player_nickname', models.CharField(max_length=64)),
                ('player_nationality', models.CharField(max_length=64)),
                ('player_birth_day', models.DateField()),
                ('player_current_role', models.CharField(max_length=64)),
                ('player_total_winnings', models.IntegerField()),
                ('player_discipline_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cybersport.disciplinemodel')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerCommandModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pc_command_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cybersport.commandmodel')),
                ('pc_player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cybersport.playermodel')),
            ],
        ),
        migrations.CreateModel(
            name='TournamentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_image', models.ImageField(upload_to='media')),
                ('tournament_name', models.CharField(max_length=64)),
                ('tournament_type', models.CharField(max_length=64)),
                ('tournament_location', models.CharField(max_length=64)),
                ('tournament_prize_pool', models.IntegerField()),
                ('tournament_start_date', models.DateField()),
                ('tournament_end_date', models.DateField()),
                ('tournament_tier', models.IntegerField()),
                ('tournament_discipline_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cybersport.disciplinemodel')),
            ],
        ),
        migrations.CreateModel(
            name='TournamentCommandModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tc_command_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cybersport.commandmodel')),
                ('tc_tournament_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cybersport.tournamentmodel')),
            ],
        ),
    ]
